version: '3.9'
services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
      - ./samples/fileload/:/fileload
      - ./samples/fileload/data:/fileload/data

  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - ./samples/fileload/:/home/jovyan/fileload
      - ./samples/permits_large/:/home/jovyan/permits_large
      - ./samples/vector_python/:/home/jovyan/vector_python
      - ./samples/pythonOM/:/home/jovyan/pythonOM
    ports:
      - 8888:8888
      - 5000:5000
    container_name: jupyter
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - REDIS_OM_URL=redis://redis:6379
    depends_on:
      - redis

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis
